const Questions = [
  {
    number: "1",
    a_1: "Define diffusion and describe its role in nutrient uptake and gaseous exchange in plants and humans",
    a_2: "Define active transport and discuss its importance as an energy-consuming process by which substances are transported against a concentration gradient, as in ion uptake by root hairs and uptake of glucose by cells in the villi",
    a_3: "Define homeostasis as the maintenance of a constant internal environment",
  },
  {
    number: "2",
    a_1: "Golgi body ",
    a_2: "Reducing sugars (Benedict's solution)",
    a_3: "Explain how energy losses occur along food chains, and discuss the efficiency of energy transfer between trophic levels",
    a_5: "Explain what is meant by an endocrine gland, with reference to the islets of Langerhans in the pancreas",
  },
  {
    number: "3",
    a_1: "Explain the basic principles of homeostasis in terms of stimulus resulting from a change in the internal environment, a corrective mechanism and negative feedback",
    a_2: "Compare the structure of typical animal and plant cells",
    a_3: "Identify, with the aid of diagrams, the main stages of mitosis",
    a_5: "Briefly describe the menstrual cycle with reference to the alternation of menstruation and ovulation, the natural variation in its length, and the fertile and infertile phases of the cycle with reference to the effects of progesterone and estrogen only",
    a_6: "State the structure of DNA in terms of the bases, sugar and phosphate groups found in each of their nucleotides ",
  },
  {
    number: "4",
    a_1: "Define and state the equation, in words only, for anaerobic respiration in humans",
    a_2: "Briefly explain how a gene that controls the production of human insulin can be inserted into bacterial DNA to produce human insulin in medical biotechnology ",
    a_3: "Describe the transfer of materials between capillaries and tissue fluid",
  },
  {
    number: "5",
    a_1: "State the roles of water in living organisms",
    a_2: "Explain the mode of action of enzymes in terms of an active site, enzyme-substrate complex, lowering of activation energy and enzyme specificity",
  },
  {
    number: "6",
    a_1: "State the function of the hepatic portal vein as the transport of blood rich in absorbed nutrients from the small intestine to the liver",
    a_2: "Describe peristalsis in terms of rhythmic wave-like contractions of the muscles to mix and propel the contents of the alimentary canal",
  },
  {
    number: "7",
    a_1: "Use a hand lens to identify and describe the stamens and stigmas of one, locally available, named, wind-pollinated flower, and examine the pollen grains using a microscope",
    a_2: "State the functions of the amniotic sac and the amniotic fluid",
    a_3: "Cell surface membrane",
    a_5: "Conduction and support – xylem vessels",
  },
  {
    number: "8",
    a_1: "Cytoplasm",
  },
  {
    number: "9",
    a_1: "Lipids such as fats from glycerol and fatty acids",
    a_2: "Distribution of chloroplasts in photosynthesis ",
  },
  {
    number: "10",
    a_1: "Explain enzyme action in terms of the ‘lock and key’ hypothesis",
  },
  {
    number: "11",
    a_1: "Mitochondria",
  },
  {
    number: "12",
    a_1: "State the functions of the amniotic sac and the amniotic fluid",
    a_2: "Outline the pathway by which water is transported from the roots to the leaves through the xylem vessels",
  },
  {
    number: "13",
    a_1: "Define diffusion and describe its role in nutrient uptake and gaseous exchange in plants and humans",
  },
  {
    number: "14",
    a_1: "Explain why observed ratios often differ from expected ratios, especially when there are small numbers of progeny ",
    a_2: "Proteins",
  },
  {
    number: "15",
    a_1: "Discuss the spread of human immunodeficiency virus (HIV) and methods by which it may be controlled",
    a_2: "Explain how the blood glucose concentration is regulated by insulin and glucagon as a homeostatic mechanism ",
    a_3: "Describe the structure of the eye as seen in front view and in horizontal section",
    a_5: "Describe the role of cilia, diaphragm, ribs and intercostal muscles in breathing",
    a_6: "Chloroplasts",
  },
  {
    number: "16",
    a_1: "Pollution due to insecticides including bioaccumulation up food chains and impact on top carnivores",
  },
  {
    number: "17",
    a_1: "Describe the maintenance of a constant body temperature in humans in terms of insulation and the role of: temperature receptors in the skin, sweating, shivering, blood vessels near the skin surface and the co-ordinating role of the hypothalamus",
  },
  {
    number: "18",
    a_1: "Explain the terms producer, consumer and trophic level in the context of food chains and food webs ",
  },
  {
    number: "19",
    a_1: "State the relationship between receptors, the central nervous system and the effectors ",
    a_2: "Nucleus",
    a_3: "Explain enzyme action in terms of the ‘lock and key’ hypothesis",
  },
  {
    number: "20",
    a_1: "Protein (biuret test)",
    a_2: "Starch (iodine in potassium iodide solution)",
    a_3: "Describe the signs, such as an increased blood glucose level and glucose in urine, and the treatment of diabetes mellitus using insulin",
    a_5: "Explain that genes may be transferred between cells. Reference should be made to the transfer of genes between organisms of the same species or different species – transgenic plants or animals ",
  },
  {
    number: "21",
    a_1: "Cytoplasm",
  },
  {
    number: "22",
    a_1: "Define and state the equation, in words and symbols, for aerobic respiration in humans",
  },
  {
    number: "23",
    a_1: "Briefly describe the non-cyclical nature of energy flow",
    a_2: "Describe the structure of the eye as seen in front view and in horizontal section",
    a_3: "Nucleus",
    a_5: "Describe the functions of main regions of the alimentary canal and the associated organs: mouth, salivary glands, oesophagus, stomach, duodenum, pancreas, gall bladder, liver, ileum, colon, rectum, anus, in relation to ingestion, digestion, absorption, assimilation and egestion of food, as appropriate",
    a_6: "Define and state the equation, in words only, for anaerobic respiration in humans",
  },
  {
    number: "24",
    a_1: "Explain how the blood glucose concentration is regulated by insulin and glucagon as a homeostatic mechanism ",
    a_2: "Explain the movement of water between plant cells, and between them and the environment in\r\nterms of water potential (calculations on water potential are not required)",
    a_3: "Protein (biuret test)",
  },
  {
    number: "25",
    a_1: "Briefly describe the menstrual cycle with reference to the alternation of menstruation and ovulation, the natural variation in its length, and the fertile and infertile phases of the cycle with reference to the effects of progesterone and estrogen only",
    a_2: "Briefly describe the menstrual cycle with reference to the alternation of menstruation and ovulation, the natural variation in its length, and the fertile and infertile phases of the cycle with reference to the effects of progesterone and estrogen only",
    a_3: "Breakdown of red blood cells",
  },
  {
    number: "26",
    a_1: "Polypeptides and proteins from amino acids",
    a_2: "Water pollution by sewage and by inorganic waste ",
  },
  {
    number: "27",
    a_1: "Outline the role of anti-diuretic hormone (ADH) in osmoregulation ",
    a_2: "Describe the structure and function of the heart in terms of muscular contraction and the working of valves",
    a_3: "Use genetic diagrams to solve problems involving monohybrid inheritance (genetic diagrams involving autosomal linkage or epistasis are not required) ",
  },
  {
    number: "28",
    a_1: "State the characteristics of, and describe the role of, the exchange surface of the alveoli in gas exchange",
  },
  {
    number: "29",
    a_1: "Define sexual reproduction as the process involving the fusion of nuclei to form a zygote and the production of genetically dissimilar offspring",
  },
  {
    number: "30",
    a_1: "State the relationship between receptors, the central nervous system and the effectors ",
  },
  {
    number: "31",
    a_1: "Outline the relationship between DNA, genes and chromosomes",
    a_2: "Explain why observed ratios often differ from expected ratios, especially when there are small numbers of progeny ",
    a_3: "Red blood cells – haemoglobin and oxygen transport ",
    a_5: "Define and state the equation, in words only, for anaerobic respiration in humans",
  },
  {
    number: "32",
    a_1: "Predict the results of simple crosses with expected ratios of 3:1 and 1:1, using the terms homozygous, heterozygous, F1 generation and F2 generation ",
  },
  {
    number: "33",
    a_1: "Explain the mode of action of enzymes in terms of an active site, enzyme-substrate complex, lowering of activation energy and enzyme specificity",
  },
  {
    number: "34",
    a_1: "State that each gene is a sequence of nucleotides, as part of a DNA molecule ",
    a_2: "Breakdown of red blood cells",
  },
  {
    number: "35",
    a_1: "Describe the structure of the eye as seen in front view and in horizontal section",
  },
  {
    number: "36",
    a_1: "Describe mutation as a change in the structure of a gene such as in sickle cell anaemia, or in the chromosome number, such as the 47 chromosomes in the condition known as Down syndrome",
  },
  {
    number: "37",
    a_1: "Describe the maintenance of a constant body temperature in humans in terms of insulation and the role of: temperature receptors in the skin, sweating, shivering, blood vessels near the skin surface and the co-ordinating role of the hypothalamus",
    a_2: "Compare, using fresh specimens, an insect-pollinated and a wind-pollinated flower",
    a_3: "Identify the positions and explain the functions of xylem vessels, phloem (sieve tube elements and companion cells) in sections of a herbaceous dicotyledonous leaf and stem, using the light microscope",
    a_5: "Name radiation and chemicals as factors which may increase the rate of mutation",
    a_6: "Carbohydrates",
  },
  {
    number: "38",
    a_1: "Polypeptides and proteins from amino acids",
    a_2: "Explain the mode of action of enzymes in terms of an active site, enzyme-substrate complex, lowering of activation energy and enzyme specificity",
  },
  {
    number: "39",
    a_1: "Describe the role of cilia, diaphragm, ribs and intercostal muscles in breathing",
  },
  {
    number: "40",
    a_1: "Define diffusion and describe its role in nutrient uptake and gaseous exchange in plants and humans",
  },
  {
    number: "41",
    a_1: "Endoplasmic reticulum",
    a_2: "Define asexual reproduction as the process resulting in the production of genetically identical offspring from one parent ",
  },
  {
    number: "42",
    a_1: "Discuss the social and ethical implications of genetic engineering, with reference to a named example ",
  },
  {
    number: "43",
    a_1: "Explain that genes may be transferred between cells. Reference should be made to the transfer of genes between organisms of the same species or different species – transgenic plants or animals ",
  },
  {
    number: "44",
    a_1: "State that each gene is a sequence of nucleotides, as part of a DNA molecule ",
  },
  {
    number: "45",
    a_1: "Endoplasmic reticulum",
    a_2: "Glycogen from glucose",
    a_3: "State the functions of the amniotic sac and the amniotic fluid",
    a_5: "Glycogen from glucose",
  },
  {
    number: "46",
    a_1: "Breakdown of alcohol",
  },
  {
    number: "47",
    a_1: "Describe the structure of a villus and its role, including the role of capillaries and lacteals in absorption",
  },
  {
    number: "48",
    a_1: "Chloroplasts",
    a_2: "Give examples of artificial selection such as in the production of economically important plants and animals",
    a_3: "Define sexual reproduction as the process involving the fusion of nuclei to form a zygote and the production of genetically dissimilar offspring",
  },
  {
    number: "49",
    a_1: "Identify on diagrams, the male reproductive system and give the functions of: testes, scrotum, sperm ducts, prostate gland, urethra and penis",
    a_2: "Predict the results of simple crosses with expected ratios of 3:1 and 1:1, using the terms homozygous, heterozygous, F1 generation and F2 generation ",
  },
  {
    number: "50",
    a_1: "Nucleus",
  },
  {
    number: "51",
    a_1: "Outline the function of the nephron with reference to ultra-filtration and selective reabsorption in the production of urine",
    a_2: "Explain the terms dominant, recessive, codominant, homozygous, heterozygous, phenotype and genotype ",
  },
  {
    number: "52",
    a_1: "Give examples of environmental factors that act as forces of natural selection ",
    a_2: "Compare, using fresh specimens, an insect-pollinated and a wind-pollinated flower",
  },
  {
    number: "53",
    a_1: "State the relationship between receptors, the central nervous system and the effectors ",
    a_2: "Use a hand lens to identify and describe the stamens and stigmas of one, locally available, named, wind-pollinated flower, and examine the pollen grains using a microscope",
  },
  {
    number: "54",
    a_1: "Use a hand lens to identify and describe the stamens and stigmas of one, locally available, named, wind-pollinated flower, and examine the pollen grains using a microscope",
  },
  {
    number: "55",
    a_1: "Explain the basic principles of homeostasis in terms of stimulus resulting from a change in the internal environment, a corrective mechanism and negative feedback",
    a_2: "Explain enzyme action in terms of the ‘lock and key’ hypothesis",
  },
  {
    number: "56",
    a_1: "Distribution of chloroplasts in photosynthesis ",
    a_2: "Describe the function of the placenta and umbilical cord in relation to exchange of dissolved nutrients, gases and excretory products (structural details are not required)",
    a_3: "Reducing sugars (Benedict's solution)",
    a_5: "Transport of oxygen – red blood cells",
    a_6: "Describe the function of the placenta and umbilical cord in relation to exchange of dissolved nutrients, gases and excretory products (structural details are not required)",
  },
  {
    number: "57",
    a_1: "Explain how energy losses occur along food chains, and discuss the efficiency of energy transfer between trophic levels",
  },
  {
    number: "58",
    a_1: "Define sexual reproduction as the process involving the fusion of nuclei to form a zygote and the production of genetically dissimilar offspring",
    a_2: "Briefly explain how a gene that controls the production of human insulin can be inserted into bacterial DNA to produce human insulin in medical biotechnology ",
    a_3: "Define excretion and explain the importance of removing nitrogenous and other compounds from the body",
    a_5: "Explain how the blood glucose concentration is regulated by insulin and glucagon as a homeostatic mechanism ",
  },
  {
    number: "59",
    a_1: "State that each gene is a sequence of nucleotides, as part of a DNA molecule ",
    a_2: "Describe the functions of enzymes (e.g. amylase, maltase, protease, lipase) in digestion, listing the substrates and end-products",
    a_3: "Mitochondria",
  },
  {
    number: "60",
    a_1: "Describe the functions of main regions of the alimentary canal and the associated organs: mouth, salivary glands, oesophagus, stomach, duodenum, pancreas, gall bladder, liver, ileum, colon, rectum, anus, in relation to ingestion, digestion, absorption, assimilation and egestion of food, as appropriate",
  },
  {
    number: "61",
    a_1: "Fats",
    a_2: "Platelets – fibrinogen to fibrin, causing clotting",
    a_3: "Define and state the equation, in words only, for anaerobic respiration in humans",
    a_5: "Define diffusion and describe its role in nutrient uptake and gaseous exchange in plants and humans",
  },
  {
    number: "62",
    a_1: "Describe the structure of a villus and its role, including the role of capillaries and lacteals in absorption",
  },
  {
    number: "63",
    a_1: "Breakdown of alcohol",
  },
  {
    number: "64",
    a_1: "Outline the role of anti-diuretic hormone (ADH) in osmoregulation ",
    a_2: "Polypeptides and proteins from amino acids",
    a_3: "Nucleus",
  },
  {
    number: "65",
    a_1: "Identify on diagrams, the female reproductive system and give the functions of: ovaries, oviducts, uterus, cervix and vagina ",
    a_2: "State the functions of the sepals, petals, anthers and carpels ",
  },
  {
    number: "66",
    a_1: "Describe how carbon is cycled within an ecosystem and outline the role of forests and oceans as carbon sinks",
    a_2: "Describe how carbon is cycled within an ecosystem and outline the role of forests and oceans as carbon sinks",
    a_3: "State the roles of water in living organisms",
    a_5: "Cell surface membrane",
    a_6: "State the equation, in words and symbols, for photosynthesis",
  },
  {
    number: "67",
    a_1: "Explain the mode of action of enzymes in terms of an active site, enzyme-substrate complex, lowering of activation energy and enzyme specificity",
  },
  {
    number: "68",
    a_1: "Relate the structure of arteries, veins and capillaries to their functions",
  },
  {
    number: "69",
    a_1: "Discuss the social and ethical implications of genetic engineering, with reference to a named example ",
    a_2: "Outline the process of pollination and distinguish between self-pollination and cross-pollination",
  },
  {
    number: "70",
    a_1: "Explain the terms producer, consumer and trophic level in the context of food chains and food webs ",
    a_2: "Identify, with the aid of diagrams, the main stages of meiosis (names of the sub-divisions of prophase are not required) ",
  },
  {
    number: "71",
    a_1: "Identify on diagrams and name the larynx, trachea, bronchi, bronchioles, alveoli and associated capillaries",
  },
  {
    number: "72",
    a_1: "Explain that genes may be transferred between cells. Reference should be made to the transfer of genes between organisms of the same species or different species – transgenic plants or animals ",
  },
  {
    number: "73",
    a_1: "Use a hand lens to identify and describe the stamens and stigmas of one, locally available, named, wind-pollinated flower, and examine the pollen grains using a microscope",
    a_2: "Plasma – transport of blood cells, ions, soluble food substances, hormones, carbon dioxide, urea, vitamins, plasma proteins",
    a_3: "State that each gene is a sequence of nucleotides, as part of a DNA molecule ",
    a_5: "Define and state the equation, in words only, for anaerobic respiration in humans",
  },
  {
    number: "74",
    a_1: "Outline the cardiac cycle in terms of what happens during systole and diastole (histology of the heart muscle, names of nerves and transmitter substances are not required)",
  },
  {
    number: "75",
    a_1: "Describe how carbon is cycled within an ecosystem and outline the role of forests and oceans as carbon sinks",
    a_2: "Discuss the function of the brain and spinal cord in producing a co-ordinated response as a result of a specific stimulus in a reflex action",
  },
  {
    number: "76",
    a_1: "Cytoplasm",
    a_2: "Lipids such as fats from glycerol and fatty acids",
  },
  {
    number: "77",
    a_1: "Explain enzyme action in terms of the ‘lock and key’ hypothesis",
    a_2: "Name radiation and chemicals as factors which may increase the rate of mutation",
  },
  {
    number: "78",
    a_1: "Vascular bundles in transport",
    a_2: "Protein (biuret test)",
  },
  {
    number: "79",
    a_1: "Outline the relationship between DNA, genes and chromosomes",
    a_2: "Describe and interpret pyramids of numbers and biomass ",
  },
  {
    number: "80",
    a_1: "State the function of the hepatic portal vein as the transport of blood rich in absorbed nutrients from the small intestine to the liver",
    a_2: "Discuss the social and ethical implications of genetic engineering, with reference to a named example ",
  },
  {
    number: "81",
    a_1: "Name radiation and chemicals as factors which may increase the rate of mutation",
  },
  {
    number: "82",
    a_1: "Describe the effects of excessive consumption of alcohol: reduced self-control, depressant, effect on reaction times, damage to liver and social implications",
    a_2: "Compare the structure of typical animal and plant cells",
  },
  {
    number: "83",
    a_1: "Outline the mechanism of dialysis in the case of kidney failure",
    a_2: "Briefly describe the non-cyclical nature of energy flow",
    a_3: "Cytoplasm",
  },
  {
    number: "84",
    a_1: "Stomata and mesophyll cells in gaseous exchange",
  },
  {
    number: "85",
    a_1: "Describe the determination of sex in humans – XX and XY chromosomes ",
  },
  {
    number: "86",
    a_1: "State the importance of mitosis in growth, repair and asexual reproduction",
    a_2: "Describe and interpret pyramids of numbers and biomass ",
  },
  {
    number: "87",
    a_1: "State how meiosis and fertilisation can lead to variation",
    a_2: "How wilting occurs",
    a_3: "Identify on a diagram of the skin: hairs, sweat glands, temperature receptors, blood vessels and fatty tissue",
    a_5: "Chloroplasts",
    a_6: "Give examples of artificial selection such as in the production of economically important plants and animals",
  },
  {
    number: "88",
    a_1: "Identify on diagrams and name the larynx, trachea, bronchi, bronchioles, alveoli and associated capillaries",
  },
  {
    number: "89",
    a_1: "State the function of the hepatic portal vein as the transport of blood rich in absorbed nutrients from the small intestine to the liver",
    a_2: "Describe the structure and function of the heart in terms of muscular contraction and the working of valves",
    a_3: "State how meiosis and fertilisation can lead to variation",
    a_5: "Identify, with the aid of diagrams, the main stages of meiosis (names of the sub-divisions of prophase are not required) ",
  },
  {
    number: "90",
    a_1: "Describe the functions of main regions of the alimentary canal and the associated organs: mouth, salivary glands, oesophagus, stomach, duodenum, pancreas, gall bladder, liver, ileum, colon, rectum, anus, in relation to ingestion, digestion, absorption, assimilation and egestion of food, as appropriate",
  },
  {
    number: "91",
    a_1: "State the functions of the sepals, petals, anthers and carpels ",
  },
  {
    number: "92",
    a_1: "State the importance of mitosis in growth, repair and asexual reproduction",
    a_2: "State the importance of mitosis in growth, repair and asexual reproduction",
    a_3: "Outline the functions of sensory neurones, relay neurones and motor neurones ",
    a_5: "Proteins",
    a_6: "Define a hormone as a chemical substance, produced by a gland, carried by the blood, which alters the activity of one or more specific target organs and is then destroyed by the liver ",
  },
  {
    number: "93",
    a_1: "Describe and interpret pyramids of numbers and biomass ",
  },
  {
    number: "94",
    a_1: "State the functions of the membrane systems and organelles identified above",
  },
  {
    number: "95",
    a_1: "Plasma – transport of blood cells, ions, soluble food substances, hormones, carbon dioxide, urea, vitamins, plasma proteins",
  },
  {
    number: "96",
    a_1: "Ribosomes",
  },
  {
    number: "97",
    a_1: "State the principal functions of component parts of the eye in producing a focused image of near and distant objects on the retina ",
    a_2: "White blood cells – phagocytosis, antibody formation and tissue rejection",
  },
  {
    number: "98",
    a_1: "Give examples of artificial selection such as in the production of economically important plants and animals",
  },
  {
    number: "99",
    a_1: "Briefly explain how a gene that controls the production of human insulin can be inserted into bacterial DNA to produce human insulin in medical biotechnology ",
  },
  {
    number: "100",
    a_1: "Endoplasmic reticulum",
  },
  {
    number: "101",
    a_1: "Explain the need for the production of genetically identical cells",
    a_2: "Describe the effect of lactic acid in muscles during exercise",
  },
  {
    number: "102",
    a_1: "Pollution due to insecticides including bioaccumulation up food chains and impact on top carnivores",
  },
  {
    number: "103",
    a_1: "Discuss the social and ethical implications of genetic engineering, with reference to a named example ",
    a_2: "Give examples of environmental factors that act as forces of natural selection ",
  },
  {
    number: "104",
    a_1: "Outline the cardiac cycle in terms of what happens during systole and diastole (histology of the heart muscle, names of nerves and transmitter substances are not required)",
  },
  {
    number: "105",
    a_1: "State that each gene is a sequence of nucleotides, as part of a DNA molecule ",
    a_2: "Absorption – root hair cells",
  },
  {
    number: "106",
    a_1: "Name radiation and chemicals as factors which may increase the rate of mutation",
    a_2: "Outline the pathway by which water is transported from the roots to the leaves through the xylem vessels",
    a_3: "Explain what is meant by an endocrine gland, with reference to the islets of Langerhans in the pancreas",
    a_5: "Define asexual reproduction as the process resulting in the production of genetically identical offspring from one parent ",
    a_6: "Identify on diagrams, the female reproductive system and give the functions of: ovaries, oviducts, uterus, cervix and vagina ",
  },
  {
    number: "107",
    a_1: "Describe the role of cilia, diaphragm, ribs and intercostal muscles in breathing",
    a_2: "Investigate and discuss the effects of varying light intensity, carbon dioxide concentration and temperature on the rate of photosynthesis (e.g. in submerged aquatic plant)",
    a_3: "Explain how the blood glucose concentration is regulated by insulin and glucagon as a homeostatic mechanism ",
    a_5: "Outline the relationship between DNA, genes and chromosomes",
    a_6: "Fats (ethanol emulsion)",
  },
  {
    number: "108",
    a_1: "Identify on diagrams and name the larynx, trachea, bronchi, bronchioles, alveoli and associated capillaries",
    a_2: "Identify on diagrams and name the larynx, trachea, bronchi, bronchioles, alveoli and associated capillaries",
  },
  {
    number: "109",
    a_1: "State the equation, in words and symbols, for photosynthesis",
    a_2: "Identify and draw, using a hand lens if necessary, the sepals, petals, stamens and carpels of one, locally available, named, insect-pollinated, dicotyledonous flower, and examine the pollen grains using a microscope ",
    a_3: "Compare, using fresh specimens, an insect-pollinated and a wind-pollinated flower",
    a_5: "Describe the determination of sex in humans – XX and XY chromosomes ",
    a_6: "Identify the positions and explain the functions of xylem vessels, phloem (sieve tube elements and companion cells) in sections of a herbaceous dicotyledonous leaf and stem, using the light microscope",
  },
  {
    number: "110",
    a_1: "Describe the removal of carbon dioxide from the lungs, including the role of the carbonic anhydrase enzyme",
    a_2: "State the function of the hepatic portal vein as the transport of blood rich in absorbed nutrients from the small intestine to the liver",
  },
  {
    number: "111",
    a_1: "Outline the pathway by which water is transported from the roots to the leaves through the xylem vessels",
    a_2: "Carbohydrates",
    a_3: "Describe the effect of lactic acid in muscles during exercise",
    a_5: "Relate the structure of arteries, veins and capillaries to their functions",
    a_6: "Water pollution by sewage and by inorganic waste ",
    undefined: "0",
  },
  {
    number: "112",
    a_1: "Glycogen from glucose",
  },
  {
    number: "113",
    a_1: "Describe how carbon is cycled within an ecosystem and outline the role of forests and oceans as carbon sinks",
  },
  {
    number: "114",
    a_1: "Outline the function of the nephron with reference to ultra-filtration and selective reabsorption in the production of urine",
  },
  {
    number: "115",
    a_1: "Nucleus",
  },
  {
    number: "116",
    a_1: "Carbohydrates",
    a_2: "Give examples of environmental factors that act as forces of natural selection ",
  },
  {
    number: "117",
    a_1: "Describe the determination of sex in humans – XX and XY chromosomes ",
    a_2: "Describe the transfer of materials between capillaries and tissue fluid",
    a_3: "Conduction and support – xylem vessels",
    a_5: "Describe the determination of sex in humans – XX and XY chromosomes ",
    a_6: "White blood cells – phagocytosis, antibody formation and tissue rejection",
  },
  {
    number: "118",
    a_1: "Ribosomes",
    a_2: "Plasma – transport of blood cells, ions, soluble food substances, hormones, carbon dioxide, urea, vitamins, plasma proteins",
    a_3: "Cell vacuoles (large, sap-filled in plant cells, small, temporary in animal cells)",
    a_5: "Define homeostasis as the maintenance of a constant internal environment",
    a_6: "Water pollution by sewage and by inorganic waste ",
  },
  {
    number: "119",
    a_1: "Discuss light intensity, carbon dioxide concentration and temperature as limiting factors on the rate of photosynthesis",
    a_2: "Outline the role of anti-diuretic hormone (ADH) in osmoregulation ",
  },
  {
    number: "120",
    a_1: "Identify, with the aid of diagrams, the main stages of mitosis",
    a_2: "Protein (biuret test)",
    a_3: "Explain the mode of action of enzymes in terms of an active site, enzyme-substrate complex, lowering of activation energy and enzyme specificity",
    a_5: "Fats",
    a_6: "Outline the function of the nephron with reference to ultra-filtration and selective reabsorption in the production of urine",
  },
  {
    number: "121",
    a_1: "Define homeostasis as the maintenance of a constant internal environment",
    a_2: "Plasma – transport of blood cells, ions, soluble food substances, hormones, carbon dioxide, urea, vitamins, plasma proteins",
    a_3: "State the importance of mitosis in growth, repair and asexual reproduction",
    a_5: "Ribosomes",
    a_6: "Explain the terms producer, consumer and trophic level in the context of food chains and food webs ",
  },
  {
    number: "122",
    a_1: "State the characteristics of, and describe the role of, the exchange surface of the alveoli in gas exchange",
    a_2: "Outline the role of anti-diuretic hormone (ADH) in osmoregulation ",
    a_3: "Discuss the function of the brain and spinal cord in producing a co-ordinated response as a result of a specific stimulus in a reflex action",
    a_5: "State that chlorophyll traps light energy and converts it into chemical energy for the formation of carbohydrates and their subsequent uses",
    a_6: "Identify on diagrams, the male reproductive system and give the functions of: testes, scrotum, sperm ducts, prostate gland, urethra and penis",
  },
  {
    number: "123",
    a_1: "Golgi body ",
    a_2: "Fat digestion",
    a_3: "Describe the effect of lactic acid in muscles during exercise",
    a_5: "Describe the difference between continuous and discontinuous variation and give examples of each ",
    a_6: "Describe the removal of carbon dioxide from the lungs, including the role of the carbonic anhydrase enzyme",
  },
  {
    number: "124",
    a_1: "Discuss the social and ethical implications of genetic engineering, with reference to a named example ",
  },
  {
    number: "125",
    a_1: "Explain the need for the production of genetically identical cells",
    a_2: "Describe the structure of the eye as seen in front view and in horizontal section",
    a_3: "Describe the effects of excessive consumption of alcohol: reduced self-control, depressant, effect on reaction times, damage to liver and social implications",
    a_5: "Describe fertilisation and early development of the zygote simply in terms of the formation of a ball of cells which becomes implanted in the wall of the uterus",
  },
  {
    number: "126",
    a_1: "Outline the cardiac cycle in terms of what happens during systole and diastole (histology of the heart muscle, names of nerves and transmitter substances are not required)",
    a_2: "State that DNA is used to carry the genetic code, which is used to synthesise specific polypeptides (details of transcription and translation are not required)",
  },
  {
    number: "127",
    a_1: "How wilting occurs",
    a_2: "White blood cells – phagocytosis, antibody formation and tissue rejection",
    a_3: "Explain enzyme action in terms of the ‘lock and key’ hypothesis",
  },
  {
    number: "128",
    a_1: "Proteins",
  },
  {
    number: "129",
    a_1: "Explain the basic principles of homeostasis in terms of stimulus resulting from a change in the internal environment, a corrective mechanism and negative feedback",
    a_2: "The effects of variation of air movement, temperature, humidity and light intensity on transpiration rate",
    a_3: "Fats (ethanol emulsion)",
    a_5: "Stomata and mesophyll cells in gaseous exchange",
  },
  {
    number: "130",
    a_1: "Discuss the spread of human immunodeficiency virus (HIV) and methods by which it may be controlled",
    a_2: "Define a hormone as a chemical substance, produced by a gland, carried by the blood, which alters the activity of one or more specific target organs and is then destroyed by the liver ",
  },
  {
    number: "131",
    a_1: "Outline the cardiac cycle in terms of what happens during systole and diastole (histology of the heart muscle, names of nerves and transmitter substances are not required)",
    a_2: "Carbohydrate metabolism",
  },
  {
    number: "132",
    a_1: "Absorption – root hair cells",
  },
  {
    number: "133",
    a_1: "Describe fertilisation and early development of the zygote simply in terms of the formation of a ball of cells which becomes implanted in the wall of the uterus",
    a_2: "Breakdown of red blood cells",
  },
  {
    number: "134",
    a_1: "Carbohydrates",
  },
  {
    number: "135",
    a_1: "Describe the role of cilia, diaphragm, ribs and intercostal muscles in breathing",
  },
  {
    number: "136",
    a_1: "Describe peristalsis in terms of rhythmic wave-like contractions of the muscles to mix and propel the contents of the alimentary canal",
  },
  {
    number: "137",
    a_1: "Plasma – transport of blood cells, ions, soluble food substances, hormones, carbon dioxide, urea, vitamins, plasma proteins",
    a_2: "Use genetic diagrams to solve problems involving monohybrid inheritance (genetic diagrams involving autosomal linkage or epistasis are not required) ",
  },
  {
    number: "138",
    a_1: "State the functions of the amniotic sac and the amniotic fluid",
  },
  {
    number: "139",
    a_1: "Absorption – root hair cells",
  },
  {
    number: "140",
    a_1: "Define excretion and explain the importance of removing nitrogenous and other compounds from the body",
  },
  {
    number: "141",
    a_1: "Describe the difference between continuous and discontinuous variation and give examples of each ",
  },
  {
    number: "142",
    a_1: "Cytoplasm",
  },
  {
    number: "143",
    a_1: "Give examples of environmental factors that act as forces of natural selection ",
  },
  {
    number: "144",
    a_1: "Explain how energy losses occur along food chains, and discuss the efficiency of energy transfer between trophic levels",
    a_2: "White blood cells – phagocytosis, antibody formation and tissue rejection",
    a_3: "State that DNA is used to carry the genetic code, which is used to synthesise specific polypeptides (details of transcription and translation are not required)",
  },
  {
    number: "145",
    a_1: "State that chlorophyll traps light energy and converts it into chemical energy for the formation of carbohydrates and their subsequent uses",
    a_2: "Describe the role of cilia, diaphragm, ribs and intercostal muscles in breathing",
    a_3: "Pollution due to insecticides including bioaccumulation up food chains and impact on top carnivores",
  },
  {
    number: "146",
    a_1: "State the roles of water in living organisms",
  },
  {
    number: "147",
    a_1: "Define excretion and explain the importance of removing nitrogenous and other compounds from the body",
    a_2: "Transport of oxygen – red blood cells",
  },
  {
    number: "148",
    a_1: "State the structure of DNA in terms of the bases, sugar and phosphate groups found in each of their nucleotides ",
  },
  {
    number: "149",
    a_1: "State what is meant by homologous pairs of chromosomes ",
  },
  {
    number: "150",
    a_1: "Outline the relationship between DNA, genes and chromosomes",
  },
  {
    number: "151",
    a_1: "Distribution of chloroplasts in photosynthesis ",
    a_2: "Outline the functions of sensory neurones, relay neurones and motor neurones ",
  },
  {
    number: "152",
    a_1: "Describe the effects of excessive consumption of alcohol: reduced self-control, depressant, effect on reaction times, damage to liver and social implications",
    a_2: "Explain how the blood glucose concentration is regulated by insulin and glucagon as a homeostatic mechanism ",
  },
  {
    number: "153",
    a_1: "Outline the mechanism of dialysis in the case of kidney failure",
    a_2: "Describe the function of the placenta and umbilical cord in relation to exchange of dissolved nutrients, gases and excretory products (structural details are not required)",
    a_3: "Investigate and explain the effects of temperature and pH on the rate of enzyme catalysed reactions",
  },
  {
    number: "154",
    a_1: "Stomata and mesophyll cells in gaseous exchange",
  },
  {
    number: "155",
    a_1: "Identify and draw, using a hand lens if necessary, the sepals, petals, stamens and carpels of one, locally available, named, insect-pollinated, dicotyledonous flower, and examine the pollen grains using a microscope ",
    a_2: "Discuss the social and ethical implications of genetic engineering, with reference to a named example ",
    a_3: "White blood cells – phagocytosis, antibody formation and tissue rejection",
    a_5: "State how meiosis and fertilisation can lead to variation",
    a_6: "Fat digestion",
  },
  {
    number: "156",
    a_1: "Compare the structure of typical animal and plant cells",
    a_2: "Golgi body ",
  },
  {
    number: "157",
    a_1: "Briefly describe the non-cyclical nature of energy flow",
  },
  {
    number: "158",
    a_1: "Outline the process of pollination and distinguish between self-pollination and cross-pollination",
    a_2: "Water pollution by sewage and by inorganic waste ",
    a_3: "The effects of variation of air movement, temperature, humidity and light intensity on transpiration rate",
    a_5: "Pollution due to insecticides including bioaccumulation up food chains and impact on top carnivores",
    a_6: "Breakdown of red blood cells",
  },
  {
    number: "159",
    a_1: "Use genetic diagrams to solve problems involving monohybrid inheritance (genetic diagrams involving autosomal linkage or epistasis are not required) ",
  },
  {
    number: "160",
    a_1: "Identify, with the aid of diagrams, the main stages of mitosis",
  },
  {
    number: "161",
    a_1: "Identify, with the aid of diagrams, the main stages of meiosis (names of the sub-divisions of prophase are not required) ",
    a_2: "Describe the effect of lactic acid in muscles during exercise",
  },
  {
    number: "162",
    a_1: "Outline the relationship between DNA, genes and chromosomes",
    a_2: "Explain that genes may be transferred between cells. Reference should be made to the transfer of genes between organisms of the same species or different species – transgenic plants or animals ",
    a_3: "How wilting occurs",
    a_5: "Discuss the social and ethical implications of genetic engineering, with reference to a named example ",
  },
  {
    number: "163",
    a_1: "Nucleus",
  },
  {
    number: "164",
    a_1: "Cell surface membrane",
    a_2: "Identify on diagrams and name the larynx, trachea, bronchi, bronchioles, alveoli and associated capillaries",
  },
  {
    number: "165",
    a_1: "White blood cells – phagocytosis, antibody formation and tissue rejection",
  },
  {
    number: "166",
    a_1: "Define asexual reproduction as the process resulting in the production of genetically identical offspring from one parent ",
    a_2: "Fats (ethanol emulsion)",
  },
  {
    number: "167",
    a_1: "Discuss the spread of human immunodeficiency virus (HIV) and methods by which it may be controlled",
    a_2: "Define a hormone as a chemical substance, produced by a gland, carried by the blood, which alters the activity of one or more specific target organs and is then destroyed by the liver ",
  },
  {
    number: "168",
    a_1: "Red blood cells – haemoglobin and oxygen transport ",
    a_2: "State the relationship between receptors, the central nervous system and the effectors ",
  },
  {
    number: "169",
    a_1: "Identify on diagrams, the female reproductive system and give the functions of: ovaries, oviducts, uterus, cervix and vagina ",
  },
  {
    number: "170",
    a_1: "Define asexual reproduction as the process resulting in the production of genetically identical offspring from one parent ",
  },
  {
    number: "171",
    a_1: "Conduction and support – xylem vessels",
    a_2: "Identify on diagrams, the female reproductive system and give the functions of: ovaries, oviducts, uterus, cervix and vagina ",
    a_3: "Describe the removal of carbon dioxide from the lungs, including the role of the carbonic anhydrase enzyme",
    a_5: "Protein (biuret test)",
    a_6: "State the relationship between receptors, the central nervous system and the effectors ",
  },
  {
    number: "172",
    a_1: "Plasma – transport of blood cells, ions, soluble food substances, hormones, carbon dioxide, urea, vitamins, plasma proteins",
  },
  {
    number: "173",
    a_1: "Identify on diagrams, the female reproductive system and give the functions of: ovaries, oviducts, uterus, cervix and vagina ",
    a_2: "Identify on diagrams and name the larynx, trachea, bronchi, bronchioles, alveoli and associated capillaries",
    a_3: "Define excretion and explain the importance of removing nitrogenous and other compounds from the body",
    a_5: "Describe the removal of carbon dioxide from the lungs, including the role of the carbonic anhydrase enzyme",
  },
  {
    number: "174",
    a_1: "Lipids such as fats from glycerol and fatty acids",
  },
  {
    number: "175",
    a_1: "Describe the removal of carbon dioxide from the lungs, including the role of the carbonic anhydrase enzyme",
  },
  {
    number: "176",
    a_1: "Define sexual reproduction as the process involving the fusion of nuclei to form a zygote and the production of genetically dissimilar offspring",
    a_2: "State the functions of the membrane systems and organelles identified above",
    a_3: "Water pollution by sewage and by inorganic waste ",
    a_5: "Cell surface membrane",
    a_6: "State the roles of water in living organisms",
  },
  {
    number: "177",
    a_1: "Define excretion and explain the importance of removing nitrogenous and other compounds from the body",
  },
  {
    number: "178",
    a_1: "List the different ABO blood groups and all possible combinations for the donor and recipient in blood transfusions",
    a_2: "Use genetic diagrams to solve problems involving monohybrid inheritance (genetic diagrams involving autosomal linkage or epistasis are not required) ",
    a_3: "Reducing sugars (Benedict's solution)",
    a_5: "Glycogen from glucose",
    a_6: "Platelets – fibrinogen to fibrin, causing clotting",
  },
  {
    number: "179",
    a_1: "Identify on diagrams, the female reproductive system and give the functions of: ovaries, oviducts, uterus, cervix and vagina ",
    a_2: "State that the nervous system – brain, spinal cord and nerves, serves to co-ordinate and regulate bodily functions ",
  },
  {
    number: "180",
    a_1: "Identify the positions and explain the functions of xylem vessels, phloem (sieve tube elements and companion cells) in sections of a herbaceous dicotyledonous leaf and stem, using the light microscope",
    a_2: "Describe the structure of the eye as seen in front view and in horizontal section",
    a_3: "State that variation and competition lead to differential survival of, and reproduction by, those organisms best fitted to the environment ",
    a_5: "Briefly explain how a gene that controls the production of human insulin can be inserted into bacterial DNA to produce human insulin in medical biotechnology ",
  },
  {
    number: "181",
    a_1: "Describe and interpret pyramids of numbers and biomass ",
    a_2: "Define sexual reproduction as the process involving the fusion of nuclei to form a zygote and the production of genetically dissimilar offspring",
    a_3: "Describe the growth of the pollen tube and its entry into the ovule followed by fertilisation (production of endosperm and details of development are not required) ",
    a_5: "Polypeptides and proteins from amino acids",
    a_6: "Explain how energy losses occur along food chains, and discuss the efficiency of energy transfer between trophic levels",
  },
  {
    number: "182",
    a_1: "Outline the process of pollination and distinguish between self-pollination and cross-pollination",
    a_2: "Describe the transfer of materials between capillaries and tissue fluid",
    a_3: "Describe the role of cilia, diaphragm, ribs and intercostal muscles in breathing",
    a_5: "Explain the terms producer, consumer and trophic level in the context of food chains and food webs ",
    a_6: "Carbohydrates",
  },
  {
    number: "183",
    a_1: "Describe the intake of carbon dioxide and water by plants",
    a_2: "Glycogen from glucose",
  },
  {
    number: "184",
    a_1: "Identify on diagrams and name the larynx, trachea, bronchi, bronchioles, alveoli and associated capillaries",
    a_2: "Cell vacuoles (large, sap-filled in plant cells, small, temporary in animal cells)",
    a_3: "Carbohydrate metabolism",
    a_5: "Outline the functions of sensory neurones, relay neurones and motor neurones ",
  },
  {
    number: "185",
    a_1: "Breakdown of alcohol",
  },
  {
    number: "186",
    a_1: "Red blood cells – haemoglobin and oxygen transport ",
  },
  {
    number: "187",
    a_1: "Define active transport and discuss its importance as an energy-consuming process by which substances are transported against a concentration gradient, as in ion uptake by root hairs and uptake of glucose by cells in the villi",
    a_2: "State the functions of the amniotic sac and the amniotic fluid",
  },
  {
    number: "188",
    a_1: "Fats (ethanol emulsion)",
    a_2: "Define and state the equation, in words only, for anaerobic respiration in humans",
    a_3: "Breakdown of red blood cells",
    a_5: "Conduction and support – xylem vessels",
    a_6: "Cytoplasm",
  },
  {
    number: "189",
    a_1: "Discuss the function of the brain and spinal cord in producing a co-ordinated response as a result of a specific stimulus in a reflex action",
    a_2: "Golgi body ",
    a_3: "Explain co-dominance and multiple alleles with reference to the inheritance of the ABO blood group phenotypes (A, B, AB and O) and the gene alleles (Iᴬ, Iᴮ and Iᴼ)",
    a_5: "Describe the intake of carbon dioxide and water by plants",
  },
  {
    number: "190",
    a_1: "Explain why observed ratios often differ from expected ratios, especially when there are small numbers of progeny ",
    a_2: "Chloroplasts",
    a_3: "Describe the function of the placenta and umbilical cord in relation to exchange of dissolved nutrients, gases and excretory products (structural details are not required)",
  },
  {
    number: "191",
    a_1: "Predict the results of simple crosses with expected ratios of 3:1 and 1:1, using the terms homozygous, heterozygous, F1 generation and F2 generation ",
  },
  {
    number: "192",
    a_1: "Identify on a diagram of the skin: hairs, sweat glands, temperature receptors, blood vessels and fatty tissue",
  },
  {
    number: "193",
    a_1: "Briefly describe the menstrual cycle with reference to the alternation of menstruation and ovulation, the natural variation in its length, and the fertile and infertile phases of the cycle with reference to the effects of progesterone and estrogen only",
  },
  {
    number: "194",
    a_1: "Describe coronary heart disease in terms of the occlusion of coronary arteries and list the possible causes, such as diet, stress and smoking, stating the possible preventative measures",
  },
  {
    number: "195",
    a_1: "List the different ABO blood groups and all possible combinations for the donor and recipient in blood transfusions",
    a_2: "Outline the mechanism of dialysis in the case of kidney failure",
    a_3: "Briefly explain how a gene that controls the production of human insulin can be inserted into bacterial DNA to produce human insulin in medical biotechnology ",
  },
  {
    number: "196",
    a_1: "Conduction and support – xylem vessels",
  },
  {
    number: "197",
    a_1: "Explain the terms dominant, recessive, codominant, homozygous, heterozygous, phenotype and genotype ",
    a_2: "Discuss the spread of human immunodeficiency virus (HIV) and methods by which it may be controlled",
    a_3: "Explain the mode of action of enzymes in terms of an active site, enzyme-substrate complex, lowering of activation energy and enzyme specificity",
  },
  {
    number: "198",
    a_1: "Explain the terms dominant, recessive, codominant, homozygous, heterozygous, phenotype and genotype ",
    a_2: "How wilting occurs",
    a_3: "Describe the removal of carbon dioxide from the lungs, including the role of the carbonic anhydrase enzyme",
    a_5: "State the structure of DNA in terms of the bases, sugar and phosphate groups found in each of their nucleotides ",
    a_6: "List the different ABO blood groups and all possible combinations for the donor and recipient in blood transfusions",
  },
  {
    number: "199",
    a_1: "Reducing sugars (Benedict's solution)",
  },
];

module.exports = Questions;
